config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/edit'
  get 'reviews/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  get 'pages/user_profile/:id', to: 'pages#user_profile', as: 'user_profile'

  resources :tickets, only: %i[edit update show destroy] do
    resources :trades, only: %i[index show new create]
  end

  resources :events, only: %i[index show destroy new create] do
    resources :tickets, only: %i[new create]
  end

  resources :trades, only: %i[index show] do
    resources :reviews, only: %i[new create]
  end

  resources :review, only: %i[edit update]

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets

  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show destroy]

  def new
    @page_name = 'Register an event'
    @event = Event.new
  end

  def index
    @page_name = 'Events'
    if params[:search].present?
      @events = Event.where('lower(location) LIKE ?', "%#{params[:search][:location].downcase}%")
                    .where('lower(title) LIKE ?', "%#{params[:search][:title].downcase}%")
                    .page(params[:page]).per(18)
      filter_by_date unless params[:search][:date].empty?
      @events = Kaminari.paginate_array(@events).page(params[:page]).per(18)
    else
      @events = Event.all.page(params[:page]).per(18)
    end
    # @events = Event.geocoded # returns events with coordinates
    # raise
    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        image_url: helpers.asset_url('logo-yoohood.png')
      }
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def create
    @event = Event.new(event_params)
    if @event.save

      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @page_name = @event.title
    @twitter_text = "Check out this event at"
    @marker = [{
      lat: @event.latitude,
      lng: @event.longitude,
      image_url: helpers.asset_url('logo-yoohood.png')
    }]
  end

  private

  def filter_by_date
    date = Date.parse(params[:search][:date])
    @events = @events.select { |event| event.start_time > date.beginning_of_day && event.start_time < date.end_of_day }
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :start_time, :location, :category, :photo, :description)
  end
end

app/views/events/_event_form.html.erb
<div class="container padding-top-page-content">
  <div class="row justify-content-center">
    <div class="card shadow-sm m-4 p-4">
      <h2>Add a New Event</h2>
      <%= simple_form_for @event do |f| %>
        <%= f.input :title, label: 'Event Name' %>
        <%= f.input :start_time %>
        <%= f.input :location %>
        <%= f.input :category %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="d-none d-md-block" id="map" data-markers="<%= @markers.to_json %>"data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        <%= link_to "Cancel", events_path, class: 'btn_red float-left', data: { confirm: 'Are you sure?' } %>
        <%= f.button :submit, class: 'btn_blue float-right' %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container padding-top-page-content">

  <% if @events.count > 0 %>
    <div class="d-none d-md-block" id="map" data-markers="<%= @markers.to_json %>"data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <%= render 'shared/event_card', events: @events %>
  <% else %>
    <div class="col-sm-12 col-md-6">
      <h2>No available events.</h2>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= render 'event_form' %>

app/views/events/show.html.erb
<div class="container padding-top-page-content">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-7">
      <div class="card">
        <div class="card-title">
          <% placeholder_url = "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&auto=format&fit=crop&w=2467&q=80" %>
          <%= image_tag @event.photo.url.presence ? @event.photo.url : placeholder_url, class: "pic", alt: "event cover" %>
          <h2 class="p-2">
            <%= @event.title %>
          </h2>
        </div>
        <div class="card-body">
          <div class="card-text">
            <p>local: <%= @event.location %></p>
            <p><%= @event.description %></p>
            <% if @event.tickets.count == 0 %>

              <p>No available tickets</p>

            <% else %>

              <% @event.tickets.each do |ticket| %>
                <% next if ticket.trades.count > 0 %>
                <!-- only show available tickets -->


                <%= link_to ticket_path(ticket) do %>
                  <div class="card p-1 m-1 shadow-lg flex-row justify-content-between">

                    <p class="card-text p-3">
                      <i class="fas fa-dollar-sign mr-2"></i> <%= ticket.price / 100.0 %>
                    </p>
                    <%= link_to user_profile_path(ticket.user) do %>
                      <p class="card-text p-3">
                        <i class="fas fa-user mr-2"></i> <%= ticket.user.name %>
                      </p>
                    <% end %>
                  </div>

                <% end %>
              <% end %>
            <% end %>
          </div>
          <%= link_to "New ticket", new_event_ticket_path(@event), class: 'btn_blue float-right' %>

          <p>Share this event!</p>
          <div class="d-flex align-items-end">
            <div class="fb-share-button mr-3" data-href=<%= request.original_url %> data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>

            <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=<%= @twitter_text %>&url=<%= request.original_url %>" data-size="small">Tweet</a>
          </div>

        </div>
      </div>
      <%= link_to "Back", events_path, class: "my-2 btn_blue float-left" %>
      <%= link_to "Delete", event_path(@event), method: :delete, class: "my-2 btn_red float-right", data: { confirm: 'Are You Sure?'} %>
    </div>
    <div class="offset-1 col-md-4 d-none d-md-block" id="map" data-markers="<%= @marker.to_json %>"data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>