config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/edit'
  get 'reviews/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  get 'pages/user_profile/:id', to: 'pages#user_profile', as: 'user_profile'

  resources :tickets, only: %i[edit update show destroy] do
    resources :trades, only: %i[index show new create]
  end

  resources :events, only: %i[index show destroy new create] do
    resources :tickets, only: %i[new create]
  end

  resources :trades, only: %i[index show] do
    resources :reviews, only: %i[new create]
  end

  resources :review, only: %i[edit update]

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event

  has_many :trades
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, except: %i[index new create]
  # before_action :set_ticket, only: %i[show edit update destroy]
  before_action :set_event, except: %i[index destroy show]
  # before_action :set_event, only: %i[new create edit show update]

  def index
    @page_name = 'Tickets'
    @tickets = Ticket.all
  end

  def show
    @page_name = @ticket.event.title
  end

  def new
    @page_name = 'Register a ticket'
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.event = @event
    if @ticket.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @page_name = 'Edit your ticket'
  end

  def update
    @ticket.update(ticket_params)
    redirect_to event_path(@ticket.event)
  end

  def destroy
    @ticket.destroy
    redirect_to events_path
  end

  private

  def ticket_params
    price = (params[:ticket][:price].split(' ')[1].to_f * 100).to_i
    params[:ticket][:price] = price
    params.require(:ticket).permit(:price, :seat, :area)
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id]) if params[:event_id].present?
  end
end

app/views/tickets/_form.html.erb
<div class="container padding-top-page-content" >
  <div class="row justify-content-center">
    <div class="card">
      <div class="card-title p-4">
        <h1>Add a ticket to <%= @event.title %></h1>
      </div>
      <div class="card-body">
        <%= simple_form_for [@event, @ticket] do |f| %>
          <%= f.input :price, as: :string, input_html: { class: 'currency' } %>
          <%= f.input :seat %>
          <%= f.input :area %>
          <%= link_to 'Back', event_path(@event), class: "btn_red" %>
          <%= f.submit class: "btn_blue float-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tickets/edit.html.erb
<%= render 'form', ticket: @ticket %>

app/views/tickets/index.html.erb
<% @tickets.each do |ticket| %>
  <p><%= ticket.price %></p>
  <p><%= ticket.seat %></p>
  <p><%= ticket.area %></p>
<% end %>

app/views/tickets/new.html.erb
<%= render 'form', ticket: @ticket %>

app/views/tickets/show.html.erb
<div class="container padding-top-page-content fix-height-container">
  <div class="row justify-content-center mt-4">
    <div class="col-sm-12 col-md-4">
      <div class="card p-4">
        <p>Price: <%= @ticket.price %></p>
        <p>Seat: <%= @ticket.seat %></p>
        <p>Area: <%= @ticket.area %></p>
      </div>
      <% if  @ticket.user == current_user%>
        <%= link_to 'Edit', edit_ticket_path(@ticket), class: "btn_blue float-right mt-2" %>
      <% else %>
        <%= link_to 'Buy', new_ticket_trade_path(@ticket), class: "btn_blue float-right mt-2" %>
      <% end %>
      <%= link_to 'Back', event_path(@ticket.event), class: "btn_red float-left mt-2" %>
    </div>
  </div>
</div>