config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/edit'
  get 'reviews/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  get 'pages/user_profile/:id', to: 'pages#user_profile', as: 'user_profile'

  resources :tickets, only: %i[edit update show destroy] do
    resources :trades, only: %i[index show new create]
  end

  resources :events, only: %i[index show destroy new create] do
    resources :tickets, only: %i[new create]
  end

  resources :trades, only: %i[index show] do
    resources :reviews, only: %i[new create]
  end

  resources :review, only: %i[edit update]

end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
  has_one :review

  validates :user_id, uniqueness: {
    scope: :ticket_id,
    message: "Transaction already done"
  }

  validates :status, inclusion: { in: ['confirmation pending', 'confirmed'] }
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # before_action :set_ticket, only: %i[new show create]
  # before_action :set_event, only: %i[show]

  def show
    # raise
    @trade = Trade.find(params[:id])
    @ticket = @trade.ticket
    @event = @ticket.event
    @page_name = "Tickets of #{@event.title}"
  end

  def new
    set_ticket
  end

  def create
    @trade = Trade.new
    @trade.ticket = set_ticket
    @trade.user = set_ticket.user
    if @trade.save
      redirect_to trade_path(@trade)
    else
      render :show
    end
  end

  private

  def set_event
    @event = set_ticket.event
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def trade_params
    # params.require(:trades).permit
  end
end

app/views/trades/new.html.erb
<div class="container padding-top-page-content fix-height-container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-4 mt-4">
      <div class="card mt-4">
        <div class="card-title p-4">
          <h2><%= @ticket.user.name %></h2>
        </div>
        <div class="card-body p-4">
          <div class="card-text">
            <p><%= @ticket.seat %></p>
            <p><%= @ticket.area %></p>
            <p><strong>$<%= @ticket.price / 100.0 %></strong></p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to "Cancel", :back, class: 'btn_red float-left' %>
          <%= link_to "Check Out", ticket_trades_path(@ticket), class: 'btn_blue float-right', method: 'post' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trades/show.html.erb
<div class="container padding-top-page-content">
  <div class="d-flex flex-column">
    <div class="row justify-content-center mb-5">
      <h1>CHECK OUT</h1>
    </div>
    <div class="row col-sm-12 justify-content-between p-5 m-2">
      <div class="card pt-5 px-5 col-sm-12 col-lg-5 m-2">
        <div class="card-title">
          <p class="py-2">Buyer:</p>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <% placeholder = "https://www.wittenberg.edu/sites/default/files/2018-10/nouser_0.jpg" %>
            <%= image_tag current_user.photo.url ? current_user.photo.url : placeholder , class: "avatar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <h2><%= current_user.name %></h2>
          </div>
        </div>
        <div class="card-body">
          <div class="card-text">
            <p class="text-right">Please, check your info:</p>
            <h5 class="text-right"><%= current_user.email %></h5>
          </div>
        </div>
      </div>
      <div class="card pt-5 px-5 col-sm-12 col-lg-5 m-2">
        <div class="card-title">
          <p class="py-2">Seller:</p>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <% placeholder = "https://www.wittenberg.edu/sites/default/files/2018-10/nouser_0.jpg" %>
            <%= image_tag @ticket.user.photo.url ? @ticket.user.photo.url : placeholder , class: "avatar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <h2><%= @ticket.user.name %></h2>
          </div>
        </div>
        <div class="card-body">
          <div class="card-text">
            <p class="text-right">How to contact:</p>
            <h5 class="text-right"><%= @ticket.user.email %></h5>
          </div>
        </div>
        <div class="card-text text-center my-4">
          <p><%= link_to "Add a review", new_trade_review_path(@trade), class: 'btn_blue' %></p>
        </div>
      </div>
      <div class="w-100 d-flex justify-content-between px-1 my-5">
        <p><%= link_to "back to event", event_path(@ticket.event), class: 'btn_blue' %></p>
        <p><%= link_to "back to home", events_path, class: 'btn_blue' %></p>
      </div>
    </div>
  </div>
</div>